student:
  name: Mike
  age: 18
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.int}
  greeting: hi,I'm ${student.name}

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${jdbcUrl}/${schema}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    password: ${password}

management:
  security:
    enabled: false
  server:
    port: 9091

